B2c exports 2.0 updates
ONDC-Official/ONDC-RET-Specifications pull request #139
Opened 2024-06-26 09:35 UTC by abhinavv245

2024-06-27 15:07 UTC, tanya-ondc requested changes

2024-06-27 17:02 UTC, abhinavv245 commented
Updated the PR

2024-06-28 05:13 UTC, tanyamadaan requested changes

2024-06-28 05:13 UTC, tanyamadaan commented on api/components/Examples/B2C_Exports/init/init_exports.yaml
> +          customer:
had asked to check and update this in select as well?

2024-06-28 05:13 UTC, tanyamadaan commented on api/components/Examples/B2C_Exports/on_cancel/on_cancel.yaml
> +          "@ondc/org/settlement_details":
do we need both P2 as well this settlement details for refund?

2024-06-28 05:13 UTC, tanyamadaan commented on api/components/Examples/B2C_Exports/on_cancel/on_cancel_merchant.yaml
>                  timestamp: '2023-02-03T11:35:00.000Z'
how come it is delivered ? and then being cancelled? remove timestamp

2024-06-28 05:13 UTC, tanyamadaan commented on api/components/Examples/B2C_Exports/on_cancel/on_cancel_merchant.yaml
> +                name: Status for delivery
This as well, as product is not yet delivered.

2024-06-28 05:13 UTC, tanyamadaan commented on api/components/Examples/B2C_Exports/on_cancel/on_cancel_merchant.yaml
> +          "@ondc/org/settlement_details":
?

2024-06-28 12:01 UTC, tanyamadaan approved these changes

2024-06-28 12:02 UTC, merged